# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/sqlite_lib/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "C:\\Users\\Dingus\\Desktop\\projects\\EZ_LCSC2KiCAD\\ez-lcsc-desktop-connector\\src-tauri\\migrations"
